version: '2'
services:
  neo4j:
    environment:
      NEO4J_AUTH: 'none'
    image: neo4j:3.0
    ports:
      - '7474:7474'

  neo4j-test:
    environment:
      NEO4J_AUTH: 'none'
    image: neo4j:3.0
    ports:
      - '7475:7474'

  web:
    build: .
    command: bundle exec rails server --port 3000 --binding '0.0.0.0'
    volumes:
      - .:/myapp
    volumes_from:
      - bundle
    ports:
      - '3000:3000'
    links:
      - neo4j
      - neo4j-test

  bundle:
    image: georgianmigration_web
    volumes:
      - /bundle
    command: echo "Loading up bundled gems!"
