# Bundle caching source: http://bradgessler.com/articles/docker-bundler/

version: '2'
services:
  db:
    environment:
      NEO4J_AUTH: 'none'
    image: neo4j:3.0
    ports:
      - '7474:7474'
  web:
    build: .
    command: /bin/sh -c "sleep 8; bundle exec rails server --port 3000 --binding '0.0.0.0'"
    volumes:
      - .:/myapp
      - bundle:/bundle
    ports:
      - '3000:3000'
    depends_on:
      - db
volumes:
  bundle:
    external: false
