# Bundle caching source: http://bradgessler.com/articles/docker-bundler/

version: '2'
services:
  db:
    image: neo4j:3.0
  web:
    build: .
    command: bundle exec rails server --port 3000 --binding '0.0.0.0'
    volumes:
      - .:/myapp
    volumes_from:
      - bundle
    ports:
      - '3000:3000'
    depends_on:
      - db
  bundle:
    # 'image' will vary depending on your docker-compose
    # project name. You may need to run `docker-compose build web`
    # before this works.
    image: georgian_migration_web
    command: echo "Look at me, I'm a bundle container!"
    volumes:
      - /bundle
